name: customer CI Pipeline

on:
  workflow_dispatch: 

permissions:
  id-token: write     # REQUIRED for OIDC
  contents: read

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4  
        with:
          role-to-assume: arn:aws:iam::074126659757:role/aws-github-role
          aws-region: us-east-2
        
