name: customer CI Pipeline

on:
  workflow_dispatch: 

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4  
        with:
          aws-access-key-id: AKIARCQSLCCWQKWNLXGP
          aws-secret-access-key: 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
          aws-region: us-east-2
        
